version: '3'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/taxi
      - REDIS_URI=redis://redis:6379

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
